"""Rebuild the seven artwork bundles after editing source-images/NN.webp.
Cover 01 and keepsake 50 stay in assets/images for their standalone uses.
Run: python3 scripts/pack-artwork.py
"""
from pathlib import Path
import base64
import hashlib
import json

ROOT = Path(__file__).resolve().parent.parent
PUBLIC = ROOT
MANIFEST = PUBLIC / 'js/artwork-manifest.js'
OUTPUT = PUBLIC / 'assets/artwork'
OUTPUT.mkdir(parents=True, exist_ok=True)
previous = json.loads(MANIFEST.read_text().split('export const ARTWORK = ', 1)[1].strip().removesuffix(';')) if MANIFEST.exists() else {}
manifest = {}
for start in range(1, 52, 8):
    scenes = {}
    for page in range(start, min(start + 8, 52)):
        folder = PUBLIC / 'assets/images' if page in (1, 50) else ROOT / 'source-images'
        image = (folder / f'{page:02d}.webp').read_bytes()
        scenes[str(page)] = 'data:image/webp;base64,' + base64.b64encode(image).decode()
    data = json.dumps(scenes, separators=(',', ':')).encode()
    name = f'scenes-{start:02d}-{hashlib.sha256(data).hexdigest()[:10]}.json'
    (OUTPUT / name).write_bytes(data)
    for page in scenes:
        manifest[page] = 'assets/artwork/' + name
MANIFEST.write_text('// Generated by scripts/pack-artwork.py\nexport const ARTWORK = ' + json.dumps(manifest, indent=2) + ';\n')
for obsolete in set(previous.values()) - set(manifest.values()):
    path = PUBLIC / obsolete
    if path.parent == OUTPUT:
        path.unlink(missing_ok=True)
print('Packed all 51 illustrations.')
